@baseUrl=http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY0ODE0MDc5OSwiZXhwIjoxNjUwNzMyNzk5fQ.cS3yD6WjYzjjlPx8C2yORRqC1z-RYmGbP-9nt_VIAZ0
###
POST {{baseUrl}}/planned-workload/plan-workload
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "startDate": "03-19-2022",
    "reason": "Early Bird",
    "plannedWorkloads": [
        {
	        "workload": 28,
            "contributedValueId": 1,
            "committedWorkloadId": 1
        },
        {
	        "workload": 8,
            "contributedValueId": 2,
            "committedWorkloadId": 1
        }
    ]
}

